### ISSUE TITLE
TODO list for production

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedora-tagger#70]
This is a list of things we should fix up before we push the new version to production.
- [x] #68 
- [x] #69 
- [x] Fix keyboard focus issue after adding tags.
- [x] Add proper unique constraints to DB in stg.
- [x] Release new RPM.
- [x] Make sure fedmsg_meta_fedora_infrastructure>=0.1.3 is deployed to value{01.stg,03}.
